// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stallions.Server.Data;

#nullable disable

namespace Stallions.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010035555_V2Phase3AuctionClose")]
    partial class V2Phase3AuctionClose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AuctionListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("AuctionListingId", "AmountIncGst");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudFarmUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("ListingId");

                    b.HasIndex("StudFarmUserId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.EnquiryMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EnquiryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReadByRecipient")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("EnquiryMessages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BuyerFeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StallionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudFarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StallionId");

                    b.HasIndex("Status", "SeasonId");

                    b.HasIndex("StudFarmId", "Status");

                    b.ToTable("Listings", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.NominationBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BuyerSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FarmSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("NominationBindings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.OutboundEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("SentAt", "FailedAt", "NextAttemptAt");

                    b.ToTable("OutboundEmails");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyerFeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ChargeGracePeriodHours")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumBidIncrement")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("OfferExpiryDays")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardListingFeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PlatformSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e771265-0000-4000-8000-000000000001"),
                            BuyerFeeIncGst = 150m,
                            ChargeGracePeriodHours = 2,
                            MinimumBidIncrement = 25m,
                            OfferExpiryDays = 7,
                            StandardListingFeeIncGst = 990m,
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.ProcessedPaymentEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedPaymentEvents");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BalancePayableToStudIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("BidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyerFeeExGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BuyerFeeGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BuyerFeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChargeAttemptStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChargeAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChargeDueBy")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastChargeFailure")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RetryRequested")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPriceIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique()
                        .HasFilter("[BidId] IS NOT NULL AND [Status] <> 'Voided'");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("ListingId");

                    b.HasIndex("Status", "ChargeDueBy");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.SavedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProviderPaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SavedCards");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sire")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StallionDirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudFarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StallionDirectoryId");

                    b.HasIndex("StudFarmId");

                    b.ToTable("Stallions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArionId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DamName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SireName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StallionId")
                        .HasColumnType("int");

                    b.Property<Guid>("StudDirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArionId");

                    b.HasIndex("StallionId");

                    b.HasIndex("StudDirectoryId");

                    b.ToTable("StallionDirectories");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("StallionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StallionId");

                    b.ToTable("StallionImages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionSeasonSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FeeExGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PendingCheckoutExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingCheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StallionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudFarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaiverReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StallionId", "SeasonId")
                        .IsUnique();

                    b.HasIndex("StudFarmId", "SeasonId");

                    b.ToTable("StallionSeasonSubscriptions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ArionStudId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Town")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArionStudId");

                    b.ToTable("StudDirectories");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ABN")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StudDirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudDirectoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudFarms");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.TermsDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("TermsDocuments");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedTermsAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcceptedTermsVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PaymentCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentCustomerProvider")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("SuppressBidConfirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] <> ''");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.HasBaseType("Stallions.Server.Data.Entities.Listing");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNoReserve")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumBidIncrement")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ReservePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("WinningBidId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WinningBidId");

                    b.ToTable("AuctionListings", (string)null);
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Bid", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.AuctionListing", "AuctionListing")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Bids")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionListing");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Enquiries")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Listing", "Listing")
                        .WithMany("Enquiries")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "StudFarmUser")
                        .WithMany()
                        .HasForeignKey("StudFarmUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("StudFarmUser");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.EnquiryMessage", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Enquiry", "Enquiry")
                        .WithMany("Messages")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enquiry");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Season", "Season")
                        .WithMany("Listings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Stallion", "Stallion")
                        .WithMany("Listings")
                        .HasForeignKey("StallionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.StudFarm", "StudFarm")
                        .WithMany("Listings")
                        .HasForeignKey("StudFarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Stallion");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.NominationBinding", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "AcknowledgedBy")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.Purchase", "Purchase")
                        .WithOne("NominationBinding")
                        .HasForeignKey("Stallions.Server.Data.Entities.NominationBinding", "PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcknowledgedBy");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.PlatformSettings", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Bid", "Bid")
                        .WithMany()
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Listing", "Listing")
                        .WithMany("Purchases")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Buyer");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.SavedCard", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "OpenedBy")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OpenedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.StallionDirectory", "StallionDirectory")
                        .WithMany()
                        .HasForeignKey("StallionDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.StudFarm", "StudFarm")
                        .WithMany("Stallions")
                        .HasForeignKey("StudFarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StallionDirectory");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionDirectory", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.StudDirectory", "StudDirectory")
                        .WithMany("Stallions")
                        .HasForeignKey("StudDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudDirectory");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionImage", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Stallion", "Stallion")
                        .WithMany("Images")
                        .HasForeignKey("StallionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stallion");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionSeasonSubscription", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Stallion", "Stallion")
                        .WithMany()
                        .HasForeignKey("StallionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.StudFarm", "StudFarm")
                        .WithMany()
                        .HasForeignKey("StudFarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Season");

                    b.Navigation("Stallion");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.StudDirectory", "StudDirectory")
                        .WithMany()
                        .HasForeignKey("StudDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.User", "User")
                        .WithOne("StudFarm")
                        .HasForeignKey("Stallions.Server.Data.Entities.StudFarm", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudDirectory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.TermsDocument", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Listing", null)
                        .WithOne()
                        .HasForeignKey("Stallions.Server.Data.Entities.AuctionListing", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Bid", "WinningBid")
                        .WithMany()
                        .HasForeignKey("WinningBidId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("WinningBid");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.Navigation("Enquiries");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.Navigation("NominationBinding");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudDirectory", b =>
                {
                    b.Navigation("Stallions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Stallions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bids");

                    b.Navigation("Enquiries");

                    b.Navigation("Purchases");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
