// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stallions.Server.Data;

#nullable disable

namespace Stallions.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AuctionListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("AuctionListingId", "AmountIncGst");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudFarmUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("ListingId");

                    b.HasIndex("StudFarmUserId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.EnquiryMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EnquiryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReadByRecipient")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("EnquiryMessages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PlatformFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StallionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudFarmId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StallionId");

                    b.HasIndex("Status", "SeasonId");

                    b.HasIndex("StudFarmId", "Status");

                    b.ToTable("Listings", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.NominationBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BuyerSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FarmSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("NominationBindings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MareBreed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MareRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PlatformFeeExGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PlatformFeeGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PlatformFeeIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPriceIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("ListingId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Colour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sire")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StudFarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudFarmId");

                    b.ToTable("Stallions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("StallionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StallionId");

                    b.ToTable("StallionImages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ABN")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudFarms");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.HasBaseType("Stallions.Server.Data.Entities.Listing");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNoReserve")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumBidIncrement")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ReservePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("WinningBidId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WinningBidId");

                    b.ToTable("AuctionListings", (string)null);
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.FixedPriceListing", b =>
                {
                    b.HasBaseType("Stallions.Server.Data.Entities.Listing");

                    b.Property<decimal>("PriceIncGst")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("int");

                    b.ToTable("FixedPriceListings", (string)null);
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Bid", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.AuctionListing", "AuctionListing")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Bids")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionListing");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Enquiries")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Listing", "Listing")
                        .WithMany("Enquiries")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "StudFarmUser")
                        .WithMany()
                        .HasForeignKey("StudFarmUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("StudFarmUser");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.EnquiryMessage", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Enquiry", "Enquiry")
                        .WithMany("Messages")
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enquiry");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Season", "Season")
                        .WithMany("Listings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Stallion", "Stallion")
                        .WithMany("Listings")
                        .HasForeignKey("StallionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.StudFarm", "StudFarm")
                        .WithMany("Listings")
                        .HasForeignKey("StudFarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Stallion");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.NominationBinding", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "AcknowledgedBy")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.Purchase", "Purchase")
                        .WithOne("NominationBinding")
                        .HasForeignKey("Stallions.Server.Data.Entities.NominationBinding", "PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcknowledgedBy");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Bid", "Bid")
                        .WithMany()
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Stallions.Server.Data.Entities.User", "Buyer")
                        .WithMany("Purchases")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Listing", "Listing")
                        .WithMany("Purchases")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Buyer");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "OpenedBy")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OpenedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.StudFarm", "StudFarm")
                        .WithMany("Stallions")
                        .HasForeignKey("StudFarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StallionImage", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Stallion", "Stallion")
                        .WithMany("Images")
                        .HasForeignKey("StallionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stallion");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "User")
                        .WithOne("StudFarm")
                        .HasForeignKey("Stallions.Server.Data.Entities.StudFarm", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Listing", null)
                        .WithOne()
                        .HasForeignKey("Stallions.Server.Data.Entities.AuctionListing", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stallions.Server.Data.Entities.Bid", "WinningBid")
                        .WithMany()
                        .HasForeignKey("WinningBidId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("WinningBid");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.FixedPriceListing", b =>
                {
                    b.HasOne("Stallions.Server.Data.Entities.Listing", null)
                        .WithOne()
                        .HasForeignKey("Stallions.Server.Data.Entities.FixedPriceListing", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Enquiry", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Listing", b =>
                {
                    b.Navigation("Enquiries");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Purchase", b =>
                {
                    b.Navigation("NominationBinding");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Season", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.Stallion", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.StudFarm", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Stallions");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bids");

                    b.Navigation("Enquiries");

                    b.Navigation("Purchases");

                    b.Navigation("StudFarm");
                });

            modelBuilder.Entity("Stallions.Server.Data.Entities.AuctionListing", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
